### ISSUE TITLE
"THIS IS MINE" 

### ISSUE THREAD

**Issue by syedshanu** [technet2/Wiki#13]
https://technet2.github.io/Wiki/articles/34960.user-page-syed-shanu.html

**Comment by ProjectPete** [comment]
ERROR #OWN-1.1 - Couldn't find the GitHub file in the body of the ticket. - Ref issue #13, Octokit.User, "THIS IS MINE" , Error: TryGetGithubFileFromIssueBody: This function was expecting a URL in the issue description that starts with 'https://github.com/technet2/Wiki/'
