### ISSUE TITLE
THIS IS MINE

### ISSUE THREAD

**Issue by pituach** [technet2/Wiki#15]
https://github.com/technet2/Wiki/blob/master/articles/32392.user-page-ronen-ariely.html

**Comment by ProjectPete** [comment]
FAILED. Check your GitHub name "pituach" (WITH speech marks) is in your TechNet biography. See mine: https://social.technet.microsoft.com/profile/pete%20laker

**Comment by ProjectPete** [comment]
FAILED. Check your GitHub name "pituach" (WITH speech marks) is in your TechNet biography. See mine: https://social.technet.microsoft.com/profile/pete%20laker

**Comment by ProjectPete** [comment]
FAILED. Check your GitHub name "pituach" (WITH speech marks) is in your TechNet biography. See mine: https://social.technet.microsoft.com/profile/pete%20laker

**Comment by ProjectPete** [comment]
FAILED. Check your GitHub name "pituach" (WITH speech marks) is in your TechNet biography. See mine: https://social.technet.microsoft.com/profile/pete%20laker

**Comment by ProjectPete** [comment]
FAILED. Check your GitHub name "pituach" (WITH speech marks) is in your TechNet biography. See mine: https://social.technet.microsoft.com/profile/pete%20laker

**Comment by ProjectPete** [comment]
SUCCESS! Your GitHub identity has been confirmed from your TechNet Biography.

**Comment by ProjectPete** [comment]
SUCCESS! Your GitHub identity has been added as a member..
