### ISSUE TITLE
THIS IS MINE

### ISSUE THREAD

**Issue by kkjha00007** [technet2/Wiki#16]
https://github.com/technet2/Wiki/blob/master/articles/37459.user-page-kamlesh-kumar.html

**Comment by ProjectPete** [comment]
FAILED. Check your GitHub name "kkjha00007" (WITH speech marks) is in your TechNet biography. See mine: https://social.technet.microsoft.com/profile/pete%20laker

**Comment by ProjectPete** [comment]
SUCCESS! Your GitHub identity has been confirmed from your TechNet Biography.

**Comment by ProjectPete** [comment]
SUCCESS! Your GitHub identity has been added as a member..
